#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MusicSelect.Resource", IsApplication=true)]

namespace MusicSelect
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int another_version = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int later = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int play_pause = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int resolve = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int select = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int technics0 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int technics1 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int technics10 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int technics11 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int technics12 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int technics13 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int technics14 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int technics15 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int technics2 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int technics3 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int technics4 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int technics5 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int technics6 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int technics7 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int technics8 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int technics9 = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int buttonAnotherVersion = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int buttonDelete = 2131099666;
			
			// aapt resource value: 0x7f06000f
			public const int buttonListenLater = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int buttonPlayPause = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int buttonResolve = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int buttonSelect = 2131099667;
			
			// aapt resource value: 0x7f060009
			public const int checkBoxAutoSkip = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int checkBoxNoVoice = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int imageViewArt = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout2 = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayout3 = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout4 = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout5 = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int seekBarTime = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int textViewArtist = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int textViewBitrate = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int textViewDuraction = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int textViewTitle = 2131099652;
			
			// aapt resource value: 0x7f06000e
			public const int toggleButtonDoubleSpeed = 2131099662;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_MusicSelectorTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
